feat(packaging): add official Debian (.deb) package generation and Linux distro support (#63) (#68)
* feat(packaging): add official Debian (.deb) package generation and Linux distro support (fixes #63)
# Committing as: guettlibot@thomas-guettler.de

* fix(packaging): address review feedback on debian packaging and release workflows
# Committing as: guettlibot@thomas-guettler.de

---------

Co-authored-by: guettlibot <guettlibot@thomas-guettler.de>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -95,17 +95,45 @@ jobs:
           ls -la /usr/share/fish/vendor_completions.d/tff.fish
           ls -la /usr/share/fish/vendor_completions.d/tff2.fish
           ls -la /usr/share/fish/vendor_completions.d/tff_linux.fish
+          # Clean up installed files so subsequent deb package tests are isolated
+          sudo rm -f /usr/local/bin/tff /usr/local/bin/tff2 /usr/local/bin/tff_linux
+          sudo systemctl stop ten-flying-fingers.service || true
 
       - name: Test release packaging & static linking
         if: matrix.cc == 'gcc'
         run: |
-          bash scripts/package_release.sh "ci-test" "build-static-test" "dist-test"
+          bash scripts/package_release.sh "2.0.0-ci" "build-static-test" "dist-test"
           tar -tzvf dist-test/tff2_Linux_x86_64.tar.gz
           tar -tzvf dist-test/tff2_Linux_x86_64.tar.gz | grep -E "completions/bash/tff"
           ./dist-test/stage_linux_x86_64/tff --help
           ./dist-test/stage_linux_x86_64/tff --list || true
           ./dist-test/stage_linux_x86_64/tff2 --help
           ./dist-test/stage_linux_x86_64/tff_linux --help
+
+      - name: Test Debian (.deb) package installation & integrity
+        if: matrix.cc == 'gcc'
+        run: |
+          dpkg-deb -I dist-test/tff2_amd64.deb
+          dpkg-deb -c dist-test/tff2_amd64.deb
+          sudo dpkg -i dist-test/tff2_amd64.deb
+          which tff
+          which tff2
+          which tff_linux
+          tff --version
+          tff validate /etc/tff/tff-combos.yaml
+          systemd-analyze verify /lib/systemd/system/ten-flying-fingers.service || true
+          systemd-analyze verify /usr/lib/systemd/user/ten-flying-fingers.service || true
+          test -f /lib/udev/rules.d/99-tff.rules || test -f /usr/lib/udev/rules.d/99-tff.rules
+          test -f /usr/share/bash-completion/completions/tff
+          test -L /usr/share/bash-completion/completions/tff2
+          test -f /usr/share/zsh/site-functions/_tff
+          test -f /usr/share/fish/vendor_completions.d/tff.fish
+          test -f /usr/share/man/man1/tff.1.gz
+          sudo dpkg -P tff2
+          ! test -e /usr/bin/tff
+          ! test -e /usr/bin/tff2
+          ! test -e /usr/bin/tff_linux
+
 
   coverage:
     name: Code Coverage (gcov)
